In [8]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Prashanth\Downloads\superstore_dataset.csv")

df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer Name,Segment,Country,City,Region,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,ORD-1001,2024-01-13,2024-01-19,Standard Class,Margaret Brown,Home Office,India,Patrickmouth,East,Technology,Laptop,Laptop Model 704,289.53,4,0.04,20.41
1,ORD-1002,2024-01-16,2024-01-17,Standard Class,Amy Lee,Home Office,India,Penaport,Central,Office Supplies,Paper,Paper Model 325,234.27,9,0.18,38.01
2,ORD-1003,2024-01-04,2024-01-11,Second Class,Kelly Nelson,Consumer,India,Loriberg,East,Office Supplies,Pen,Pen Model 489,809.70,7,0.10,65.66
3,ORD-1004,2024-06-25,2024-06-30,Second Class,Benjamin Jimenez,Consumer,India,Nathanchester,South,Furniture,Bookcase,Bookcase Model 949,279.23,1,0.22,43.91
4,ORD-1005,2024-10-22,2024-10-24,First Class,Stephanie Green,Consumer,India,North Cynthia,East,Technology,Printer,Printer Model 489,710.48,1,0.20,145.37

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       200 non-null    str
 1   Order Date     200 non-null    str
 2   Ship Date      200 non-null    str
 3   Ship Mode      200 non-null    str
 4   Customer Name  200 non-null    str
 5   Segment        200 non-null    str
 6   Country        200 non-null    str
 7   City           200 non-null    str
 8   Region         200 non-null    str
 9   Category       200 non-null    str
 10  Sub-Category   200 non-null    str
 11  Product Name   200 non-null    str
 12  Sales          200 non-null    float64
 13  Quantity       200 non-null    int64
 14  Discount       200 non-null    float64
 15  Profit         200 non-null    float64
dtypes: float64(3), int64(1), str(12)
memory usage: 25.1 KB

In [10]:
df.isnull().sum()

Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer Name    0
Segment          0
Country          0
City             0
Region           0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df['Order Date'] = pd.to_datetime(df['Order Date'])

df['Ship Date'] = pd.to_datetime(df['Ship Date'])

In [13]:
df.dtypes

Order ID                    str
Order Date       datetime64[us]
Ship Date        datetime64[us]
Ship Mode                   str
Customer Name               str
Segment                     str
Country                     str
City                        str
Region                      str
Category                    str
Sub-Category                str
Product Name                str
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

In [14]:
df.to_csv("cleaned_superstore.csv", index=False)

In [15]:
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer Name,Segment,Country,City,Region,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,ORD-1001,2024-01-13,2024-01-19,Standard Class,Margaret Brown,Home Office,India,Patrickmouth,East,Technology,Laptop,Laptop Model 704,289.53,4,0.04,20.41
1,ORD-1002,2024-01-16,2024-01-17,Standard Class,Amy Lee,Home Office,India,Penaport,Central,Office Supplies,Paper,Paper Model 325,234.27,9,0.18,38.01
2,ORD-1003,2024-01-04,2024-01-11,Second Class,Kelly Nelson,Consumer,India,Loriberg,East,Office Supplies,Pen,Pen Model 489,809.70,7,0.10,65.66
3,ORD-1004,2024-06-25,2024-06-30,Second Class,Benjamin Jimenez,Consumer,India,Nathanchester,South,Furniture,Bookcase,Bookcase Model 949,279.23,1,0.22,43.91
4,ORD-1005,2024-10-22,2024-10-24,First Class,Stephanie Green,Consumer,India,North Cynthia,East,Technology,Printer,Printer Model 489,710.48,1,0.20,145.37